# Generated by Django 6.1.1 on 2026-09-05 16:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_user_profile_and_role_proxies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "release_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ADMIN", "Administration"), ("TMDB", "TMDb")],
                        db_index=True,
                        default="ADMIN",
                        max_length=10,
                    ),
                ),
                (
                    "tmdb_id",
                    models.PositiveBigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "tmdb_vote_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("tmdb_vote_count", models.PositiveIntegerField(default=0)),
                ("poster_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("title", "pk"),
            },
        ),
        migrations.CreateModel(
            name="FilmAuthorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.film"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"groups__name": "AUTHOR"},
                related_name="authored_films",
                through="cinema.FilmAuthorship",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FilmRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="cinema.film",
                    ),
                ),
                (
                    "spectator",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "SPECTATOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="film_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "AUTHOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spectator",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "SPECTATOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("spectator", "author"),
                        name="unique_spectator_author_rating",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 1), ("score__lte", 5)),
                        name="author_rating_score_between_1_and_5",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spectator",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "SPECTATOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="cinema.film",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("spectator", "film"), name="unique_spectator_favorite"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="filmauthorship",
            constraint=models.UniqueConstraint(
                fields=("film", "author"), name="unique_film_author"
            ),
        ),
        migrations.AddConstraint(
            model_name="film",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("DRAFT", "PUBLISHED", "ARCHIVED"))),
                name="film_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="film",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ("ADMIN", "TMDB"))),
                name="film_valid_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="film",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tmdb_vote_average__isnull", True),
                    models.Q(
                        ("tmdb_vote_average__gte", 0), ("tmdb_vote_average__lte", 10)
                    ),
                    _connector="OR",
                ),
                name="film_valid_tmdb_vote_average",
            ),
        ),
        migrations.AddConstraint(
            model_name="filmrating",
            constraint=models.UniqueConstraint(
                fields=("spectator", "film"), name="unique_spectator_film_rating"
            ),
        ),
        migrations.AddConstraint(
            model_name="filmrating",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 1), ("score__lte", 5)),
                name="film_rating_score_between_1_and_5",
            ),
        ),
    ]
