# Generated by Django 6.1.1 on 2026-09-06 15:17

import django.db.models.functions.text
from django.db import migrations, models

import cinema.managers


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "cinema",
            "0003_film_filmauthorship_film_authors_filmrating_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", cinema.managers.CinemaUserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="unique_user_username_ci",
            ),
        ),
    ]
